project:
  type: website
  render:
    - index.qmd
    - /slides/index.qmd
    - /tuto/r.qmd

css: custom.css


website:
  title: "Atelier tutomate sur le format `Parquet`"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: slides/index.qmd
        text: Slides
      - href: tuto/r.qmd
        text: Tutoriel R
      - href: tuto/python.qmd
        text: Tutoriel Python

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    code-annotations: hover
    code-link: true
