project:
  type: website
  render:
    - index.qmd
    - /slides/index.qmd
    - /tuto/python.qmd
    - /tuto/observable.qmd

css: custom.css

filters:
  - "vscode.lua"

website:
  title: "Atelier tutomate sur le format `Parquet`"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: slides/index.qmd
        text: Slides
      - href: tuto/r.qmd
        text: Tutoriel R
      - href: "https://observablehq.com/@linogaliana/atelier-parquet-tutomate-observable"
        text: Tutoriel Observable

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    code-annotations: hover
    code-link: true
