name: Publish slides

on: 
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          version: 1.5.57
      - name: Install system dependencies
        run: |
          sudo apt-get install libudunits2-dev \
            libgdal-dev \
            libgeos-dev \
            libproj-dev
      - name: Install R Dependencies
        uses: r-lib/actions/setup-renv@v2
        with:
          cache-version: 1
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12' 
          cache: 'pip' # caching pip dependencies          
      - run: pip install -r requirements.txt
      - name: Render website
        run: |
          rm _quarto.yml
          cp _quarto-complete.yml _quarto.yml
          quarto render --to html
      - name: Publish to GitHub Pages
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
          render: false
